//define the characters types
const characterActionTypes ={
    ADD_CHARACTER: "ADD_CHARACTER",
    REMOVE_CHARACTER:"REMOVE_CHARACTER",
    EDIT_CHARACTER:"EDIT_CHARACTER",
    FETCH_ALL_CHARACTER:"FETCH_ALL_CHARACTER",
    FETCH_SINGLE_CHARACTER:"FETCH_SINGLR_CHARACTER",
}

export default characterActionTypes;